[package]
name = "tokio-exercise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
more-asserts = "0.3.0"
time = "0.3.13"
tokio = { version = "1.20.1", features = ["full"] }
